set search_path=mrsdba;

INSERT INTO MRSDBA.MRS_STATS_SYSTEM
SELECT now(),
P1."USERS_ACTIVE_COUNT", P2."USERS_INACTIVE_COUNT", P3."SITES_COUNT",
P4."SCANNERS_COUNT", P5."STUDIES_INACTIVE_COUNT", P6."STUDIES_ACTIVE_COUNT",
P7."SUBJECTS_COUNT", P8."SCAN_SESSIONS_COUNT", P9."INSTRUMENTS_COUNT", P10."ASSESSMENTS_COUNT",
P11."QUESTIONS_COUNT"
 FROM
 (SELECT COUNT(1) "USERS_ACTIVE_COUNT" FROM CASDBA.CAS_USERS WHERE ACTIVE_FLAG='Y') P1, 
 (SELECT COUNT(1) "USERS_INACTIVE_COUNT" FROM CASDBA.CAS_USERS WHERE ACTIVE_FLAG='N') P2, 
 (SELECT COUNT(1) "SITES_COUNT" FROM MRSDBA.MRS_SITES) P3, 
 (SELECT COUNT(1) "SCANNERS_COUNT" FROM MRS_SCANNERS_VW) P4, 
 (SELECT COUNT(1) "STUDIES_INACTIVE_COUNT" FROM MRS_STUDIES_VW WHERE EXPIRATION_DATE<now()) P5, 
 (SELECT COUNT(1) "STUDIES_ACTIVE_COUNT" FROM MRS_STUDIES_VW WHERE EXPIRATION_DATE>=now()) P6, 
 (SELECT COUNT(1) "SUBJECTS_COUNT" FROM MRS_SUBJECTS_VW) P7, 
 (SELECT COUNT(1) "SCAN_SESSIONS_COUNT" FROM MRS_SCAN_SESSIONS_VW) P8, 
 (SELECT COUNT(1) "INSTRUMENTS_COUNT" FROM MRS_INST_VW) P9, 
 (SELECT COUNT(1) "ASSESSMENTS_COUNT" FROM MRS_ASSESSMENTS_VW) P10,
 (SELECT COUNT(1) "QUESTIONS_COUNT" FROM MRS_ASSESSMENT_RESPONSES_VW) P11;
